var obj_cod_cont = {  
                      africa:"Africa", 
                      america:"Am&eacute;rica", 
                      asia:"Asia", 
                      europa:"Europa", 
                      oceania:"Ocean&iacute;a"
}

var obj_cont_ac = {  
                      africa:"Africa", 
                      america:"América", 
                      asia:"Asia", 
                      europa:"Europa", 
                      oceania:"Oceanía"
}

var obj_cod_pais = {  
                      AF:"Afganist&aacute;n", 
                      AL:"Albania", 
                      DE:"Alemania", 
                      AD:"Andorra", 
                      AO:"Angola", 
                      AI:"Anguilla", 
                      AQ:"Ant&aacute;rtida", 
                      AG:"Antigua y Barbuda", 
                      AN:"Antillas Holandesas", 
                      SA:"Arabia Saud&iacute;", 
                      DZ:"Argelia", 
                      AR:"Argentina", 
                      AM:"Armenia", 
                      AW:"Aruba", 
                      AU:"Australia", 
                      AT:"Austria",  
                      AZ:"Azerbaiy&aacute;n",  
                      BS:"Bahamas",  
                      BH:"Bahrein",  
                      BD:"Bangladesh",  
                      BB:"Barbados",  
                      BE:"B&eacute;lgica",  
                      BZ:"Belice",  
                      BJ:"Benin",  
                      BM:"Bermudas",  
                      BY:"Bielorrusia",  
                      MM:"Birmania",  
                      BO:"Bolivia",  
                      BA:"Bosnia y Herzegovina",  
                      BW:"Botswana",  
                      BR:"Brasil",  
                      BN:"Brunei",  
                      BG:"Bulgaria",  
                      BF:"Burkina Faso",  
                      BI:"Burundi",  
                      BT:"But&aacute;n",  
                      CV:"Cabo Verde",  
                      KH:"Camboya",  
                      CM:"Camer&uacute;n",  
                      CA:"Canad&aacute;",  
                      TD:"Chad",  
                      CL:"Chile",  
                      CN:"China",  
                      CY:"Chipre",  
                      VA:"Ciudad del Vaticano",  
                      CO:"Colombia",  
                      KM:"Comores",  
                      CG:"Congo",  
                      CD:"Congo, Rep&uacute;blica Democr&aacute;tica",  
                      KR:"Corea",  
                      KP:"Corea del Norte",  
                      CI:"Costa de Marf&iacute;l",  
                      CR:"Costa Rica",  
                      HR:"Croacia (Hrvatska)",  
                      CU:"Cuba",  
                      DK:"Dinamarca",  
                      DJ:"Djibouti",  
                      DM:"Dominica",  
                      EC:"Ecuador",  
                      EG:"Egipto",  
                      SV:"El Salvador",  
                      AE:"Emiratos &aacute;rabes Unidos",  
                      ER:"Eritrea",  
                      SI:"Eslovenia",  
                      ES:"Espa&ntilde;a",  
                      US:"Estados Unidos",  
                      EE:"Estonia",  
                      ET:"Etiop&iacute;a",  
                      FJ:"Fiji",  
                      PH:"Filipinas",  
                      FI:"Finlandia",  
                      FR:"Francia",  
                      GA:"Gab&oacute;n",  
                      GM:"Gambia",  
                      GE:"Georgia",  
                      GH:"Ghana",  
                      GI:"Gibraltar",  
                      GD:"Granada",  
                      GR:"Grecia",  
                      GL:"Groenlandia",  
                      GP:"Guadalupe",  
                      GU:"Guam",  
                      GT:"Guatemala",  
                      GY:"Guayana",  
                      GF:"Guayana Francesa",  
                      GN:"Guinea",  
                      GQ:"Guinea Ecuatorial",  
                      GW:"Guinea-Bissau",  
                      HT:"Hait&iacute;",  
                      HN:"Honduras",  
                      HU:"Hungr&iacute;a",  
                      IN:"India",  
                      ID:"Indonesia",  
                      IQ:"Irak",  
                      IR:"Ir&aacute;n",  
                      IE:"Irlanda",  
                      BV:"Isla Bouvet",  
                      CX:"Isla de Christmas",  
                      IS:"Islandia",  
                      KY:"Islas Caim&aacute;n",  
                      CK:"Islas Cook",  
                      CC:"Islas de Cocos o Keeling",  
                      FO:"Islas Faroe",  
                      HM:"Islas Heard y McDonald",  
                      FK:"Islas Malvinas",  
                      MP:"Islas Marianas del Norte",  
                      MH:"Islas Marshall",  
                      UM:"Islas menores de Estados Unidos",  
                      PW:"Islas Palau",  
                      SB:"Islas Salom&oacute;n",  
                      SJ:"Islas Svalbard y Jan Mayen",  
                      TK:"Islas Tokelau",  
                      TC:"Islas Turks y Caicos",  
                      VI:"Islas V&iacute;rgenes (EE.UU.)",  
                      VG:"Islas V&iacute;rgenes (Reino Unido)",  
                      WF:"Islas Wallis y Futuna",  
                      IL:"Israel",  
                      IT:"Italia",  
                      JM:"Jamaica",  
                      JP:"Jap&oacute;n",  
                      JO:"Jordania",  
                      KZ:"Kazajist&aacute;n",  
                      KE:"Kenia",  
                      KG:"Kirguizist&aacute;n",  
                      KI:"Kiribati",  
                      KW:"Kuwait",  
                      LA:"Laos",  
                      LS:"Lesotho",  
                      LV:"Letonia",  
                      LB:"L&iacute;bano",  
                      LR:"Liberia",  
                      LY:"Libia",  
                      LI:"Liechtenstein",  
                      LT:"Lituania",  
                      LU:"Luxemburgo",  
                      MK:"Macedonia",  
                      MG:"Madagascar",  
                      MY:"Malasia",  
                      MW:"Malawi",  
                      MV:"Maldivas",  
                      ML:"Mal&iacute;",  
                      MT:"Malta",  
                      MA:"Marruecos",  
                      MQ:"Martinica",  
                      MU:"Mauricio",  
                      MR:"Mauritania",  
                      YT:"Mayotte",  
                      MX:"M&eacute;xico",  
                      FM:"Micronesia",  
                      MD:"Moldavia",  
                      MC:"M&oacute;naco",  
                      MN:"Mongolia",  
                      MS:"Montserrat",  
                      MZ:"Mozambique",  
                      NA:"Namibia",  
                      NR:"Nauru",  
                      NP:"Nepal",  
                      NI:"Nicaragua",  
                      NE:"N&iacute;ger",  
                      NG:"Nigeria",  
                      NU:"Niue",  
                      NF:"Norfolk",  
                      NO:"Noruega",  
                      NC:"Nueva Caledonia",  
                      NZ:"Nueva Zelanda",  
                      OM:"Om&aacute;n",  
                      NL:"Pa&iacute;ses Bajos",  
                      PA:"Panam&aacute;",  
                      PG:"Pap&uacute;a Nueva Guinea",  
                      PK:"Paquist&aacute;n",  
                      PY:"Paraguay",  
                      PE:"Per&uacute;",  
                      PN:"Pitcairn",  
                      PF:"Polinesia Francesa",  
                      PL:"Polonia",  
                      PT:"Portugal",  
                      PR:"Puerto Rico",  
                      QA:"Qatar",  
                      UK:"Reino Unido",  
                      CF:"Rep&uacute;blica Centroafricana",  
                      CZ:"Rep&uacute;blica Checa",  
                      ZA:"Rep&uacute;blica de Sud&aacute;frica",  
                      DO:"Rep&uacute;blica Dominicana",  
                      SK:"Rep&uacute;blica Eslovaca",  
                      RE:"Reuni&oacute;n",  
                      RW:"Ruanda",  
                      RO:"Rumania",  
                      RU:"Rusia",  
                      EH:"Sahara Occidental",  
                      KN:"Saint Kitts y Nevis",  
                      WS:"Samoa",  
                      AS:"Samoa Americana",  
                      SM:"San Marino",  
                      VC:"San Vicente y Granadinas",  
                      SH:"Santa Helena",  
                      LC:"Santa Luc&iacute;a",  
                      ST:"Santo Tom&eacute; y Pr&iacute;ncipe",  
                      SN:"Senegal",  
                      SC:"Seychelles",  
                      SL:"Sierra Leona",  
                      SG:"Singapur",  
                      SY:"Siria",  
                      SO:"Somalia",  
                      LK:"Sri Lanka",  
                      PM:"St. Pierre y Miquelon",  
                      SZ:"Suazilandia",  
                      SD:"Sud&aacute;n",  
                      SE:"Suecia",  
                      CH:"Suiza",  
                      SR:"Surinam",  
                      TH:"Tailandia",  
                      TW:"Taiw&aacute;n",  
                      TZ:"Tanzania",  
                      TJ:"Tayikist&aacute;n",  
                      TF:"Territorios franceses del Sur",  
                      TP:"Timor Oriental",  
                      TG:"Togo",  
                      TO:"Tonga",  
                      TT:"Trinidad y Tobago",  
                      TN:"T&uacute;nez",  
                      TM:"Turkmenist&aacute;n",  
                      TR:"Turqu&iacute;a",  
                      TV:"Tuvalu",  
                      UA:"Ucrania",  
                      UG:"Uganda",  
                      UY:"Uruguay",  
                      UZ:"Uzbekist&aacute;n",  
                      VU:"Vanuatu",  
                      VE:"Venezuela",  
                      VN:"Vietnam",  
                      YE:"Yemen",  
                      YU:"Yugoslavia",  
                      ZM:"Zambia",  
                      ZW:"Zimbabue"
};


var cod_p = {  
                      AF:"Afganistan", 
                      AL:"Albania", 
                      DE:"Alemania", 
                      AD:"Andorra", 
                      AO:"Angola", 
                      AI:"Anguilla", 
                      AQ:"Antartida", 
                      AG:"Antigua y Barbuda", 
                      AN:"Antillas Holandesas", 
                      SA:"Arabia Saudi", 
                      DZ:"Argelia", 
                      AR:"Argentina", 
                      AM:"Armenia", 
                      AW:"Aruba", 
                      AU:"Australia", 
                      AT:"Austria",  
                      AZ:"Azerbaiyan",  
                      BS:"Bahamas",  
                      BH:"Bahrein",  
                      BD:"Bangladesh",  
                      BB:"Barbados",  
                      BE:"Belgica",  
                      BZ:"Belice",  
                      BJ:"Benin",  
                      BM:"Bermudas",  
                      BY:"Bielorrusia",  
                      MM:"Birmania",  
                      BO:"Bolivia",  
                      BA:"Bosnia y Herzegovina",  
                      BW:"Botswana",  
                      BR:"Brasil",  
                      BN:"Brunei",  
                      BG:"Bulgaria",  
                      BF:"Burkina Faso",  
                      BI:"Burundi",  
                      BT:"Butan",  
                      CV:"Cabo Verde",  
                      KH:"Camboya",  
                      CM:"Camerun",  
                      CA:"Canada",  
                      TD:"Chad",  
                      CL:"Chile",  
                      CN:"China",  
                      CY:"Chipre",  
                      VA:"Ciudad del Vaticano",  
                      CO:"Colombia",  
                      KM:"Comores",  
                      CG:"Congo",  
                      CD:"Congo, Republica Democratica",  
                      KR:"Corea",  
                      KP:"Corea del Norte",  
                      CI:"Costa de Marfil",  
                      CR:"Costa Rica",  
                      HR:"Croacia (Hrvatska)",  
                      CU:"Cuba",  
                      DK:"Dinamarca",  
                      DJ:"Djibouti",  
                      DM:"Dominica",  
                      EC:"Ecuador",  
                      EG:"Egipto",  
                      SV:"El Salvador",  
                      AE:"Emiratos arabes Unidos",  
                      ER:"Eritrea",  
                      SI:"Eslovenia",  
                      ES:"España",  
                      US:"Estados Unidos",  
                      EE:"Estonia",  
                      ET:"Etiopia",  
                      FJ:"Fiji",  
                      PH:"Filipinas",  
                      FI:"Finlandia",  
                      FR:"Francia",  
                      GA:"Gabon",  
                      GM:"Gambia",  
                      GE:"Georgia",  
                      GH:"Ghana",  
                      GI:"Gibraltar",  
                      GD:"Granada",  
                      GR:"Grecia",  
                      GL:"Groenlandia",  
                      GP:"Guadalupe",  
                      GU:"Guam",  
                      GT:"Guatemala",  
                      GY:"Guayana",  
                      GF:"Guayana Francesa",  
                      GN:"Guinea",  
                      GQ:"Guinea Ecuatorial",  
                      GW:"Guinea-Bissau",  
                      HT:"Haiti",  
                      HN:"Honduras",  
                      HU:"Hungria",  
                      IN:"India",  
                      ID:"Indonesia",  
                      IQ:"Irak",  
                      IR:"Iran",  
                      IE:"Irlanda",  
                      BV:"Isla Bouvet",  
                      CX:"Isla de Christmas",  
                      IS:"Islandia",  
                      KY:"Islas Caiman",  
                      CK:"Islas Cook",  
                      CC:"Islas de Cocos o Keeling",  
                      FO:"Islas Faroe",  
                      HM:"Islas Heard y McDonald",  
                      FK:"Islas Malvinas",  
                      MP:"Islas Marianas del Norte",  
                      MH:"Islas Marshall",  
                      UM:"Islas menores de Estados Unidos",  
                      PW:"Islas Palau",  
                      SB:"Islas Salomon",  
                      SJ:"Islas Svalbard y Jan Mayen",  
                      TK:"Islas Tokelau",  
                      TC:"Islas Turks y Caicos",  
                      VI:"Islas Virgenes (EE.UU.)",  
                      VG:"Islas Virgenes (Reino Unido)",  
                      WF:"Islas Wallis y Futuna",  
                      IL:"Israel",  
                      IT:"Italia",  
                      JM:"Jamaica",  
                      JP:"Japon",  
                      JO:"Jordania",  
                      KZ:"Kazajistan",  
                      KE:"Kenia",  
                      KG:"Kirguizistan",  
                      KI:"Kiribati",  
                      KW:"Kuwait",  
                      LA:"Laos",  
                      LS:"Lesotho",  
                      LV:"Letonia",  
                      LB:"Libano",  
                      LR:"Liberia",  
                      LY:"Libia",  
                      LI:"Liechtenstein",  
                      LT:"Lituania",  
                      LU:"Luxemburgo",  
                      MK:"Macedonia",  
                      MG:"Madagascar",  
                      MY:"Malasia",  
                      MW:"Malawi",  
                      MV:"Maldivas",  
                      ML:"Mali",  
                      MT:"Malta",  
                      MA:"Marruecos",  
                      MQ:"Martinica",  
                      MU:"Mauricio",  
                      MR:"Mauritania",  
                      YT:"Mayotte",  
                      MX:"Mexico",  
                      FM:"Micronesia",  
                      MD:"Moldavia",  
                      MC:"Monaco",  
                      MN:"Mongolia",  
                      MS:"Montserrat",  
                      MZ:"Mozambique",  
                      NA:"Namibia",  
                      NR:"Nauru",  
                      NP:"Nepal",  
                      NI:"Nicaragua",  
                      NE:"Niger",  
                      NG:"Nigeria",  
                      NU:"Niue",  
                      NF:"Norfolk",  
                      NO:"Noruega",  
                      NC:"Nueva Caledonia",  
                      NZ:"Nueva Zelanda",  
                      OM:"Oman",  
                      NL:"Paises Bajos",  
                      PA:"Panama",  
                      PG:"Papua Nueva Guinea",  
                      PK:"Paquistan",  
                      PY:"Paraguay",  
                      PE:"Peru",  
                      PN:"Pitcairn",  
                      PF:"Polinesia Francesa",  
                      PL:"Polonia",  
                      PT:"Portugal",  
                      PR:"Puerto Rico",  
                      QA:"Qatar",  
                      UK:"Reino Unido",  
                      CF:"Republica Centroafricana",  
                      CZ:"Republica Checa",  
                      ZA:"Republica de Sudafrica",  
                      DO:"Republica Dominicana",  
                      SK:"Republica Eslovaca",  
                      RE:"Reunion",  
                      RW:"Ruanda",  
                      RO:"Rumania",  
                      RU:"Rusia",  
                      EH:"Sahara Occidental",  
                      KN:"Saint Kitts y Nevis",  
                      WS:"Samoa",  
                      AS:"Samoa Americana",  
                      SM:"San Marino",  
                      VC:"San Vicente y Granadinas",  
                      SH:"Santa Helena",  
                      LC:"Santa Lucia",  
                      ST:"Santo Tome y Principe",  
                      SN:"Senegal",  
                      SC:"Seychelles",  
                      SL:"Sierra Leona",  
                      SG:"Singapur",  
                      SY:"Siria",  
                      SO:"Somalia",  
                      LK:"Sri Lanka",  
                      PM:"St. Pierre y Miquelon",  
                      SZ:"Suazilandia",  
                      SD:"Sudan",  
                      SE:"Suecia",  
                      CH:"Suiza",  
                      SR:"Surinam",  
                      TH:"Tailandia",  
                      TW:"Taiwan",  
                      TZ:"Tanzania",  
                      TJ:"Tayikistan",  
                      TF:"Territorios franceses del Sur",  
                      TP:"Timor Oriental",  
                      TG:"Togo",  
                      TO:"Tonga",  
                      TT:"Trinidad y Tobago",  
                      TN:"Tunez",  
                      TM:"Turkmenistan",  
                      TR:"Turquia",  
                      TV:"Tuvalu",  
                      UA:"Ucrania",  
                      UG:"Uganda",  
                      UY:"Uruguay",  
                      UZ:"Uzbekistan",  
                      VU:"Vanuatu",  
                      VE:"Venezuela",  
                      VN:"Vietnam",  
                      YE:"Yemen",  
                      YU:"Yugoslavia",  
                      ZM:"Zambia",  
                      ZW:"Zimbabue"
};




var cod_pais_acento = {  
                      AF:"Afganistán", 
                      AL:"Albania", 
                      DE:"Alemania", 
                      AD:"Andorra", 
                      AO:"Angola", 
                      AI:"Anguilla", 
                      AQ:"Antártida", 
                      AG:"Antigua y Barbuda", 
                      AN:"Antillas Holandesas", 
                      SA:"Arabia Saudí", 
                      DZ:"Argelia", 
                      AR:"Argentina", 
                      AM:"Armenia", 
                      AW:"Aruba", 
                      AU:"Australia", 
                      AT:"Austria",  
                      AZ:"Azerbaiyán",  
                      BS:"Bahamas",  
                      BH:"Bahrein",  
                      BD:"Bangladesh",  
                      BB:"Barbados",  
                      BE:"Bélgica",  
                      BZ:"Belice",  
                      BJ:"Benin",  
                      BM:"Bermudas",  
                      BY:"Bielorrusia",  
                      MM:"Birmania",  
                      BO:"Bolivia",  
                      BA:"Bosnia y Herzegovina",  
                      BW:"Botswana",  
                      BR:"Brasil",  
                      BN:"Brunei",  
                      BG:"Bulgaria",  
                      BF:"Burkina Faso",  
                      BI:"Burundi",  
                      BT:"Bután",  
                      CV:"Cabo Verde",  
                      KH:"Camboya",  
                      CM:"Camerún",  
                      CA:"Canadá",  
                      TD:"Chad",  
                      CL:"Chile",  
                      CN:"China",  
                      CY:"Chipre",  
                      VA:"Ciudad del Vaticano",  
                      CO:"Colombia",  
                      KM:"Comores",  
                      CG:"Congo",  
                      CD:"Congo, República Democrática",  
                      KR:"Corea",  
                      KP:"Corea del Norte",  
                      CI:"Costa de Marfíl",  
                      CR:"Costa Rica",  
                      HR:"Croacia (Hrvatska)",  
                      CU:"Cuba",  
                      DK:"Dinamarca",  
                      DJ:"Djibouti",  
                      DM:"Dominica",  
                      EC:"Ecuador",  
                      EG:"Egipto",  
                      SV:"El Salvador",  
                      AE:"Emiratos árabes Unidos",  
                      ER:"Eritrea",  
                      SI:"Eslovenia",  
                      ES:"España",  
                      US:"Estados Unidos",  
                      EE:"Estonia",  
                      ET:"Etiopía",  
                      FJ:"Fiji",  
                      PH:"Filipinas",  
                      FI:"Finlandia",  
                      FR:"Francia",  
                      GA:"Gabón",  
                      GM:"Gambia",  
                      GE:"Georgia",  
                      GH:"Ghana",  
                      GI:"Gibraltar",  
                      GD:"Granada",  
                      GR:"Grecia",  
                      GL:"Groenlandia",  
                      GP:"Guadalupe",  
                      GU:"Guam",  
                      GT:"Guatemala",  
                      GY:"Guayana",  
                      GF:"Guayana Francesa",  
                      GN:"Guinea",  
                      GQ:"Guinea Ecuatorial",  
                      GW:"Guinea-Bissau",  
                      HT:"Haití",  
                      HN:"Honduras",  
                      HU:"Hungría",  
                      IN:"India",  
                      ID:"Indonesia",  
                      IQ:"Irak",  
                      IR:"Irán",  
                      IE:"Irlanda",  
                      BV:"Isla Bouvet",  
                      CX:"Isla de Christmas",  
                      IS:"Islandia",  
                      KY:"Islas Caimán",  
                      CK:"Islas Cook",  
                      CC:"Islas de Cocos o Keeling",  
                      FO:"Islas Faroe",  
                      HM:"Islas Heard y McDonald",  
                      FK:"Islas Malvinas",  
                      MP:"Islas Marianas del Norte",  
                      MH:"Islas Marshall",  
                      UM:"Islas menores de Estados Unidos",  
                      PW:"Islas Palau",  
                      SB:"Islas Salom&oacute;n",  
                      SJ:"Islas Svalbard y Jan Mayen",  
                      TK:"Islas Tokelau",  
                      TC:"Islas Turks y Caicos",  
                      VI:"Islas Vírgenes (EE.UU.)",  
                      VG:"Islas Vírgenes (Reino Unido)",  
                      WF:"Islas Wallis y Futuna",  
                      IL:"Israel",  
                      IT:"Italia",  
                      JM:"Jamaica",  
                      JP:"Japón",  
                      JO:"Jordania",  
                      KZ:"Kazajistán",  
                      KE:"Kenia",  
                      KG:"Kirguizistán",  
                      KI:"Kiribati",  
                      KW:"Kuwait",  
                      LA:"Laos",  
                      LS:"Lesotho",  
                      LV:"Letonia",  
                      LB:"Líbano",  
                      LR:"Liberia",  
                      LY:"Libia",  
                      LI:"Liechtenstein",  
                      LT:"Lituania",  
                      LU:"Luxemburgo",  
                      MK:"Macedonia",  
                      MG:"Madagascar",  
                      MY:"Malasia",  
                      MW:"Malawi",  
                      MV:"Maldivas",  
                      ML:"Malí",  
                      MT:"Malta",  
                      MA:"Marruecos",  
                      MQ:"Martinica",  
                      MU:"Mauricio",  
                      MR:"Mauritania",  
                      YT:"Mayotte",  
                      MX:"México",  
                      FM:"Micronesia",  
                      MD:"Moldavia",  
                      MC:"M&oacute;naco",  
                      MN:"Mongolia",  
                      MS:"Montserrat",  
                      MZ:"Mozambique",  
                      NA:"Namibia",  
                      NR:"Nauru",  
                      NP:"Nepal",  
                      NI:"Nicaragua",  
                      NE:"Níger",  
                      NG:"Nigeria",  
                      NU:"Niue",  
                      NF:"Norfolk",  
                      NO:"Noruega",  
                      NC:"Nueva Caledonia",  
                      NZ:"Nueva Zelanda",  
                      OM:"Omán",  
                      NL:"Países Bajos",  
                      PA:"Panamá",  
                      PG:"Papúa Nueva Guinea",  
                      PK:"Paquistán",  
                      PY:"Paraguay",  
                      PE:"Perú",  
                      PN:"Pitcairn",  
                      PF:"Polinesia Francesa",  
                      PL:"Polonia",  
                      PT:"Portugal",  
                      PR:"Puerto Rico",  
                      QA:"Qatar",  
                      UK:"Reino Unido",  
                      CF:"República Centroafricana",  
                      CZ:"República Checa",  
                      ZA:"República de Sudáfrica",  
                      DO:"República Dominicana",  
                      SK:"República Eslovaca",  
                      RE:"Reunión",  
                      RW:"Ruanda",  
                      RO:"Rumania",  
                      RU:"Rusia",  
                      EH:"Sahara Occidental",  
                      KN:"Saint Kitts y Nevis",  
                      WS:"Samoa",  
                      AS:"Samoa Americana",  
                      SM:"San Marino",  
                      VC:"San Vicente y Granadinas",  
                      SH:"Santa Helena",  
                      LC:"Santa Lucía",  
                      ST:"Santo Tomé y Príncipe",  
                      SN:"Senegal",  
                      SC:"Seychelles",  
                      SL:"Sierra Leona",  
                      SG:"Singapur",  
                      SY:"Siria",  
                      SO:"Somalia",  
                      LK:"Sri Lanka",  
                      PM:"St. Pierre y Miquelon",  
                      SZ:"Suazilandia",  
                      SD:"Sudán",  
                      SE:"Suecia",  
                      CH:"Suiza",  
                      SR:"Surinam",  
                      TH:"Tailandia",  
                      TW:"Taiwán",  
                      TZ:"Tanzania",  
                      TJ:"Tayikistán",  
                      TF:"Territorios franceses del Sur",  
                      TP:"Timor Oriental",  
                      TG:"Togo",  
                      TO:"Tonga",  
                      TT:"Trinidad y Tobago",  
                      TN:"Túnez",  
                      TM:"Turkmenistán",  
                      TR:"Turquía",  
                      TV:"Tuvalu",  
                      UA:"Ucrania",  
                      UG:"Uganda",  
                      UY:"Uruguay",  
                      UZ:"Uzbekistán",  
                      VU:"Vanuatu",  
                      VE:"Venezuela",  
                      VN:"Vietnam",  
                      YE:"Yemen",  
                      YU:"Yugoslavia",  
                      ZM:"Zambia",  
                      ZW:"Zimbabue"
};